# Generated by Django 3.2.9 on 2022-03-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/images/')),
                ('title', models.CharField(max_length=75)),
                ('desc', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
