# Generated by Django 3.2.9 on 2022-03-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_ratings_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='yalscore',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
