# Generated by Django 3.2.9 on 2022-04-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_yalscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='desc',
        ),
        migrations.AddField(
            model_name='review',
            name='userscore',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
