# Generated by Django 3.2.9 on 2022-04-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220403_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='desc',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(choices=[('0', '0'), ('20', '20'), ('40', '40'), ('60', '60'), ('80', '80'), ('100', '100')], default='0', max_length=10)),
                ('votes', models.IntegerField(default=0)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
        ),
    ]
