# Generated by Django 3.2.9 on 2022-04-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220417_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
