# Generated by Django 3.2.9 on 2022-04-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220417_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='totalscore',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='userscore',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
