# Generated by Django 3.2.9 on 2022-04-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220418_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='desc',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
